### PR TITLE
Migrate team bios to YAML

### PR DESCRIPTION
**Pull request by skrulcik**
- Use jekyll's site data to store all of the team data in a single file
- Adding/editing members is now super easy
- Unfortunately it doesn't let us center the images in the last row if
our member count isn't mod 3

### CODE REVIEW

**Comment by skrulcik** [comment]
@jez I think you suggested doing this before. It makes maintenance way easier, but it might make the new member "add yourself to the website" too easy, so I'm leaving it as a PR. Does that matter much? Any other thoughts before merging this?

**Comment by jez** [comment]
What's the point of having people add themselves to the website? To challenge them? To teach them HTML? To introduce them to Git, GitHub, and pull requests?

**Comment by yiblet** [comment]
Yeah, I wasnt completely sure if we wanted to go through with this at first, because it makes changing the website's style more difficult, but I think that the advantage of it being an awesome teaching opportunity completely outweigh the drawbacks.

**Comment by skrulcik** [comment]
Nice Socratic method Jake, the most important thing for people to learn would be to introduce them to git, github and pull requests, so this change does not hinder those learning goals. I'll go ahead and merge it!

**Pull request merged**
